language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mkdir -p build/logs
  - 'if [ $(phpenv version-name) == "5.5" ]; then sudo pecl install mongodb; fi'
  - 'if [ $(phpenv version-name) == "5.6" ]; then sudo pecl install mongodb; fi'
  - 'if [ $(phpenv version-name) == "7.0" ]; then sudo pecl install mongodb; fi'
  - 'if [ $(phpenv version-name) == "7.1" ]; then sudo pecl install mongodb; fi'

install:
  - composer install --prefer-dist --no-interaction

script:
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
